/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module UART_8N1_RX(RX, clk, rst, data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  input RX;
  wire RX;
  wire [3:0] STATE;
  wire [13:0] baud_counter;
  wire [3:0] bit_counter;
  input clk;
  wire clk;
  output [7:0] data;
  wire [7:0] data;
  wire [7:0] data_reg;
  wire rff1;
  wire rff2;
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(rff2),
    .Y(_078_)
  );
  sky130_fd_sc_hd__clkinv_1 _166_ (
    .A(STATE[1]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _167_ (
    .A(STATE[3]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__clkinv_1 _168_ (
    .A(STATE[2]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__clkinv_1 _169_ (
    .A(rst),
    .Y(_004_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _170_ (
    .A(STATE[0]),
    .SLEEP(rff2),
    .X(_082_)
  );
  sky130_fd_sc_hd__or4_1 _171_ (
    .A(STATE[1]),
    .B(STATE[3]),
    .C(STATE[2]),
    .D(STATE[0]),
    .X(_083_)
  );
  sky130_fd_sc_hd__nor4_1 _172_ (
    .A(STATE[1]),
    .B(STATE[3]),
    .C(STATE[2]),
    .D(_082_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__and3_1 _173_ (
    .A(baud_counter[2]),
    .B(baud_counter[1]),
    .C(baud_counter[0]),
    .X(_085_)
  );
  sky130_fd_sc_hd__and4_1 _174_ (
    .A(baud_counter[3]),
    .B(baud_counter[2]),
    .C(baud_counter[1]),
    .D(baud_counter[0]),
    .X(_086_)
  );
  sky130_fd_sc_hd__and2_0 _175_ (
    .A(baud_counter[4]),
    .B(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__and3_1 _176_ (
    .A(baud_counter[5]),
    .B(baud_counter[4]),
    .C(_086_),
    .X(_088_)
  );
  sky130_fd_sc_hd__and3_1 _177_ (
    .A(baud_counter[7]),
    .B(baud_counter[6]),
    .C(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__and4_1 _178_ (
    .A(baud_counter[8]),
    .B(baud_counter[7]),
    .C(baud_counter[6]),
    .D(_088_),
    .X(_090_)
  );
  sky130_fd_sc_hd__and3_1 _179_ (
    .A(baud_counter[10]),
    .B(baud_counter[9]),
    .C(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__nand4_1 _180_ (
    .A(baud_counter[11]),
    .B(baud_counter[10]),
    .C(baud_counter[9]),
    .D(_090_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand4_1 _181_ (
    .A(baud_counter[13]),
    .B(baud_counter[12]),
    .C(baud_counter[11]),
    .D(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__or4b_1 _182_ (
    .A(bit_counter[2]),
    .B(bit_counter[1]),
    .C(bit_counter[0]),
    .D_N(bit_counter[3]),
    .X(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(STATE[1]),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _184_ (
    .A1(STATE[1]),
    .A2(_094_),
    .B1(STATE[3]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(_081_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a31o_1 _186_ (
    .A1(baud_counter[12]),
    .A2(baud_counter[11]),
    .A3(_091_),
    .B1(baud_counter[13]),
    .X(_098_)
  );
  sky130_fd_sc_hd__a32o_1 _187_ (
    .A1(_093_),
    .A2(_097_),
    .A3(_098_),
    .B1(_084_),
    .B2(baud_counter[13]),
    .X(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(baud_counter[12]),
    .B(_084_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(baud_counter[8]),
    .B(baud_counter[7]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor3_1 _190_ (
    .A(baud_counter[13]),
    .B(baud_counter[8]),
    .C(baud_counter[7]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__or4b_1 _191_ (
    .A(baud_counter[9]),
    .B(baud_counter[5]),
    .C(baud_counter[3]),
    .D_N(baud_counter[6]),
    .X(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(baud_counter[12]),
    .B(baud_counter[10]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor4_1 _193_ (
    .A(baud_counter[13]),
    .B(baud_counter[11]),
    .C(_102_),
    .D(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand4_1 _194_ (
    .A(baud_counter[4]),
    .B(_085_),
    .C(_100_),
    .D(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand3_1 _195_ (
    .A(baud_counter[12]),
    .B(baud_counter[10]),
    .C(baud_counter[6]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor4_1 _196_ (
    .A(baud_counter[13]),
    .B(baud_counter[11]),
    .C(baud_counter[9]),
    .D(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor4_1 _197_ (
    .A(baud_counter[8]),
    .B(baud_counter[7]),
    .C(baud_counter[5]),
    .D(baud_counter[3]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__and4_1 _198_ (
    .A(baud_counter[4]),
    .B(_085_),
    .C(_107_),
    .D(_108_),
    .X(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(_096_),
    .B(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(STATE[2]),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xor2_1 _201_ (
    .A(baud_counter[12]),
    .B(_092_),
    .X(_112_)
  );
  sky130_fd_sc_hd__o21ai_0 _202_ (
    .A1(_111_),
    .A2(_112_),
    .B1(_099_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(baud_counter[11]),
    .B(_083_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a31o_1 _204_ (
    .A1(baud_counter[10]),
    .A2(baud_counter[9]),
    .A3(_090_),
    .B1(baud_counter[11]),
    .X(_114_)
  );
  sky130_fd_sc_hd__and2_0 _205_ (
    .A(baud_counter[11]),
    .B(rff2),
    .X(_115_)
  );
  sky130_fd_sc_hd__nor4bb_1 _206_ (
    .A(baud_counter[10]),
    .B(baud_counter[6]),
    .C_N(baud_counter[5]),
    .D_N(baud_counter[9]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__and4b_1 _207_ (
    .A_N(baud_counter[12]),
    .B(baud_counter[11]),
    .C(baud_counter[1]),
    .D(baud_counter[0]),
    .X(_117_)
  );
  sky130_fd_sc_hd__nor3b_1 _208_ (
    .A(baud_counter[4]),
    .B(baud_counter[2]),
    .C_N(baud_counter[3]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand4_1 _209_ (
    .A(_101_),
    .B(_116_),
    .C(_117_),
    .D(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o21ai_0 _210_ (
    .A1(_115_),
    .A2(_119_),
    .B1(STATE[2]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(_096_),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand3_1 _212_ (
    .A(_092_),
    .B(_114_),
    .C(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand4_1 _213_ (
    .A(_079_),
    .B(_080_),
    .C(_081_),
    .D(_115_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a31oi_1 _214_ (
    .A1(_083_),
    .A2(_122_),
    .A3(_123_),
    .B1(_113_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _215_ (
    .A1(baud_counter[9]),
    .A2(_090_),
    .B1(baud_counter[10]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(baud_counter[10]),
    .B(_084_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o31ai_1 _217_ (
    .A1(_091_),
    .A2(_111_),
    .A3(_124_),
    .B1(_125_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xor2_1 _218_ (
    .A(baud_counter[9]),
    .B(_090_),
    .X(_126_)
  );
  sky130_fd_sc_hd__a22o_1 _219_ (
    .A1(baud_counter[9]),
    .A2(_084_),
    .B1(_121_),
    .B2(_126_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _220_ (
    .A(baud_counter[8]),
    .B(_089_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(_090_),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a22o_1 _222_ (
    .A1(baud_counter[8]),
    .A2(_084_),
    .B1(_097_),
    .B2(_128_),
    .X(_072_)
  );
  sky130_fd_sc_hd__a21oi_1 _223_ (
    .A1(baud_counter[6]),
    .A2(_088_),
    .B1(baud_counter[7]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(_089_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a22o_1 _225_ (
    .A1(baud_counter[7]),
    .A2(_084_),
    .B1(_097_),
    .B2(_130_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(baud_counter[6]),
    .B(_084_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _227_ (
    .A(baud_counter[6]),
    .B(_088_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21ai_0 _228_ (
    .A1(_111_),
    .A2(_132_),
    .B1(_131_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(baud_counter[5]),
    .B(_084_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _230_ (
    .A1(baud_counter[5]),
    .A2(_087_),
    .B1(_121_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21ai_0 _231_ (
    .A1(_088_),
    .A2(_134_),
    .B1(_133_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(baud_counter[4]),
    .B(_084_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o22ai_1 _233_ (
    .A1(baud_counter[4]),
    .A2(_086_),
    .B1(_110_),
    .B2(STATE[2]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o21ai_0 _234_ (
    .A1(_087_),
    .A2(_136_),
    .B1(_135_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(baud_counter[3]),
    .B(_085_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(baud_counter[3]),
    .B(_084_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2b_1 _237_ (
    .A(_110_),
    .B_N(_120_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o31ai_1 _238_ (
    .A1(_086_),
    .A2(_137_),
    .A3(_139_),
    .B1(_138_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a31oi_1 _239_ (
    .A1(baud_counter[1]),
    .A2(baud_counter[0]),
    .A3(_083_),
    .B1(baud_counter[2]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(STATE[2]),
    .B(_119_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _241_ (
    .A1(_096_),
    .A2(_141_),
    .B1(_085_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _242_ (
    .A1(baud_counter[2]),
    .A2(_084_),
    .B1(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor2_1 _243_ (
    .A(_140_),
    .B(_143_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xnor2_1 _244_ (
    .A(baud_counter[1]),
    .B(baud_counter[0]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _245_ (
    .A(_081_),
    .B(_119_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(_115_),
    .B(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(_144_),
    .B(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a22o_1 _248_ (
    .A1(baud_counter[1]),
    .A2(_084_),
    .B1(_121_),
    .B2(_147_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(baud_counter[0]),
    .B(_146_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a22o_1 _250_ (
    .A1(baud_counter[0]),
    .A2(_084_),
    .B1(_121_),
    .B2(_148_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _251_ (
    .A(_095_),
    .B(_105_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__mux2_1 _252_ (
    .A0(data_reg[7]),
    .A1(rff2),
    .S(_149_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(data_reg[6]),
    .A1(data_reg[7]),
    .S(_149_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _254_ (
    .A0(data_reg[5]),
    .A1(data_reg[6]),
    .S(_149_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _255_ (
    .A0(data_reg[4]),
    .A1(data_reg[5]),
    .S(_149_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _256_ (
    .A0(data_reg[3]),
    .A1(data_reg[4]),
    .S(_149_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _257_ (
    .A0(data_reg[2]),
    .A1(data_reg[3]),
    .S(_149_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _258_ (
    .A0(data_reg[1]),
    .A1(data_reg[2]),
    .S(_149_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _259_ (
    .A0(data_reg[0]),
    .A1(data_reg[1]),
    .S(_149_),
    .X(_056_)
  );
  sky130_fd_sc_hd__or3_1 _260_ (
    .A(_078_),
    .B(_080_),
    .C(_105_),
    .X(_150_)
  );
  sky130_fd_sc_hd__mux2_1 _261_ (
    .A0(data_reg[7]),
    .A1(data[7]),
    .S(_150_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _262_ (
    .A0(data_reg[6]),
    .A1(data[6]),
    .S(_150_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _263_ (
    .A0(data_reg[5]),
    .A1(data[5]),
    .S(_150_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _264_ (
    .A0(data_reg[4]),
    .A1(data[4]),
    .S(_150_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _265_ (
    .A0(data_reg[3]),
    .A1(data[3]),
    .S(_150_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _266_ (
    .A0(data_reg[2]),
    .A1(data[2]),
    .S(_150_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _267_ (
    .A0(data_reg[1]),
    .A1(data[1]),
    .S(_150_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _268_ (
    .A0(data_reg[0]),
    .A1(data[0]),
    .S(_150_),
    .X(_048_)
  );
  sky130_fd_sc_hd__and2_0 _269_ (
    .A(bit_counter[1]),
    .B(bit_counter[0]),
    .X(_151_)
  );
  sky130_fd_sc_hd__o21ai_0 _270_ (
    .A1(STATE[2]),
    .A2(STATE[0]),
    .B1(_078_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__a22oi_1 _271_ (
    .A1(STATE[2]),
    .A2(_119_),
    .B1(_152_),
    .B2(_079_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__and2_0 _272_ (
    .A(_095_),
    .B(_153_),
    .X(_154_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(_109_),
    .B(_153_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21ai_0 _274_ (
    .A1(_095_),
    .A2(_109_),
    .B1(_153_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o211ai_1 _275_ (
    .A1(_095_),
    .A2(_109_),
    .B1(_151_),
    .C1(_153_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o2111ai_1 _276_ (
    .A1(_095_),
    .A2(_109_),
    .B1(_151_),
    .C1(_153_),
    .D1(bit_counter[2]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xor2_1 _277_ (
    .A(bit_counter[3]),
    .B(_158_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(_154_),
    .B(_159_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xor2_1 _279_ (
    .A(bit_counter[2]),
    .B(_157_),
    .X(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _280_ (
    .A1(_079_),
    .A2(_153_),
    .B1(_160_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _281_ (
    .A1(bit_counter[1]),
    .A2(bit_counter[0]),
    .B1(STATE[1]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(bit_counter[1]),
    .B(_156_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o31ai_1 _283_ (
    .A1(_151_),
    .A2(_156_),
    .A3(_161_),
    .B1(_162_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _284_ (
    .A(bit_counter[0]),
    .B(_155_),
    .X(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_154_),
    .B(_163_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o22ai_1 _286_ (
    .A1(_079_),
    .A2(_094_),
    .B1(_109_),
    .B2(_080_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21ai_0 _287_ (
    .A1(STATE[0]),
    .A2(_145_),
    .B1(rff2),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o21ai_0 _288_ (
    .A1(_080_),
    .A2(_105_),
    .B1(_164_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__o31ai_1 _289_ (
    .A1(_081_),
    .A2(_115_),
    .A3(_119_),
    .B1(_095_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2b_1 _290_ (
    .A_N(_082_),
    .B(_141_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _291_ (
    .A(rst),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _292_ (
    .A(rst),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _293_ (
    .A(rst),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _294_ (
    .A(rst),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _295_ (
    .A(rst),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _296_ (
    .A(rst),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _297_ (
    .A(rst),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _298_ (
    .A(rst),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _299_ (
    .A(rst),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _300_ (
    .A(rst),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _301_ (
    .A(rst),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _302_ (
    .A(rst),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _303_ (
    .A(rst),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _304_ (
    .A(rst),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _305_ (
    .A(rst),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _306_ (
    .A(rst),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _307_ (
    .A(rst),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _308_ (
    .A(rst),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _309_ (
    .A(rst),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _310_ (
    .A(rst),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _311_ (
    .A(rst),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _312_ (
    .A(rst),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _313_ (
    .A(rst),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _314_ (
    .A(rst),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _315_ (
    .A(rst),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _316_ (
    .A(rst),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _317_ (
    .A(rst),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _318_ (
    .A(rst),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _319_ (
    .A(rst),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _320_ (
    .A(rst),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _321_ (
    .A(rst),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _322_ (
    .A(rst),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _323_ (
    .A(rst),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _324_ (
    .A(rst),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _325_ (
    .A(rst),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(rst),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(rst),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(rst),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _329_ (
    .A(rst),
    .Y(_043_)
  );
  sky130_fd_sc_hd__dfrtp_1 _330_ (
    .CLK(clk),
    .D(_044_),
    .Q(bit_counter[0]),
    .RESET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_1 _331_ (
    .CLK(clk),
    .D(_045_),
    .Q(bit_counter[1]),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_1 _332_ (
    .CLK(clk),
    .D(_046_),
    .Q(bit_counter[2]),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_1 _333_ (
    .CLK(clk),
    .D(_047_),
    .Q(bit_counter[3]),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfstp_2 _334_ (
    .CLK(clk),
    .D(_000_),
    .Q(STATE[0]),
    .SET_B(_008_)
  );
  sky130_fd_sc_hd__dfrtp_1 _335_ (
    .CLK(clk),
    .D(_001_),
    .Q(STATE[1]),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__dfrtp_1 _336_ (
    .CLK(clk),
    .D(_002_),
    .Q(STATE[2]),
    .RESET_B(_010_)
  );
  sky130_fd_sc_hd__dfrtp_1 _337_ (
    .CLK(clk),
    .D(_003_),
    .Q(STATE[3]),
    .RESET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_1 _338_ (
    .CLK(clk),
    .D(_048_),
    .Q(data[0]),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_1 _339_ (
    .CLK(clk),
    .D(_049_),
    .Q(data[1]),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_1 _340_ (
    .CLK(clk),
    .D(_050_),
    .Q(data[2]),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_1 _341_ (
    .CLK(clk),
    .D(_051_),
    .Q(data[3]),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_1 _342_ (
    .CLK(clk),
    .D(_052_),
    .Q(data[4]),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_1 _343_ (
    .CLK(clk),
    .D(_053_),
    .Q(data[5]),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_1 _344_ (
    .CLK(clk),
    .D(_054_),
    .Q(data[6]),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_1 _345_ (
    .CLK(clk),
    .D(_055_),
    .Q(data[7]),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfstp_2 _346_ (
    .CLK(clk),
    .D(RX),
    .Q(rff1),
    .SET_B(_020_)
  );
  sky130_fd_sc_hd__dfstp_2 _347_ (
    .CLK(clk),
    .D(rff1),
    .Q(rff2),
    .SET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_1 _348_ (
    .CLK(clk),
    .D(_056_),
    .Q(data_reg[0]),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_1 _349_ (
    .CLK(clk),
    .D(_057_),
    .Q(data_reg[1]),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfrtp_1 _350_ (
    .CLK(clk),
    .D(_058_),
    .Q(data_reg[2]),
    .RESET_B(_024_)
  );
  sky130_fd_sc_hd__dfrtp_1 _351_ (
    .CLK(clk),
    .D(_059_),
    .Q(data_reg[3]),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_1 _352_ (
    .CLK(clk),
    .D(_060_),
    .Q(data_reg[4]),
    .RESET_B(_026_)
  );
  sky130_fd_sc_hd__dfrtp_1 _353_ (
    .CLK(clk),
    .D(_061_),
    .Q(data_reg[5]),
    .RESET_B(_027_)
  );
  sky130_fd_sc_hd__dfrtp_1 _354_ (
    .CLK(clk),
    .D(_062_),
    .Q(data_reg[6]),
    .RESET_B(_028_)
  );
  sky130_fd_sc_hd__dfrtp_1 _355_ (
    .CLK(clk),
    .D(_063_),
    .Q(data_reg[7]),
    .RESET_B(_029_)
  );
  sky130_fd_sc_hd__dfrtp_1 _356_ (
    .CLK(clk),
    .D(_064_),
    .Q(baud_counter[0]),
    .RESET_B(_030_)
  );
  sky130_fd_sc_hd__dfrtp_1 _357_ (
    .CLK(clk),
    .D(_065_),
    .Q(baud_counter[1]),
    .RESET_B(_031_)
  );
  sky130_fd_sc_hd__dfrtp_1 _358_ (
    .CLK(clk),
    .D(_066_),
    .Q(baud_counter[2]),
    .RESET_B(_032_)
  );
  sky130_fd_sc_hd__dfrtp_1 _359_ (
    .CLK(clk),
    .D(_067_),
    .Q(baud_counter[3]),
    .RESET_B(_033_)
  );
  sky130_fd_sc_hd__dfrtp_1 _360_ (
    .CLK(clk),
    .D(_068_),
    .Q(baud_counter[4]),
    .RESET_B(_034_)
  );
  sky130_fd_sc_hd__dfrtp_1 _361_ (
    .CLK(clk),
    .D(_069_),
    .Q(baud_counter[5]),
    .RESET_B(_035_)
  );
  sky130_fd_sc_hd__dfrtp_1 _362_ (
    .CLK(clk),
    .D(_070_),
    .Q(baud_counter[6]),
    .RESET_B(_036_)
  );
  sky130_fd_sc_hd__dfrtp_1 _363_ (
    .CLK(clk),
    .D(_071_),
    .Q(baud_counter[7]),
    .RESET_B(_037_)
  );
  sky130_fd_sc_hd__dfrtp_1 _364_ (
    .CLK(clk),
    .D(_072_),
    .Q(baud_counter[8]),
    .RESET_B(_038_)
  );
  sky130_fd_sc_hd__dfrtp_1 _365_ (
    .CLK(clk),
    .D(_073_),
    .Q(baud_counter[9]),
    .RESET_B(_039_)
  );
  sky130_fd_sc_hd__dfrtp_1 _366_ (
    .CLK(clk),
    .D(_074_),
    .Q(baud_counter[10]),
    .RESET_B(_040_)
  );
  sky130_fd_sc_hd__dfrtp_1 _367_ (
    .CLK(clk),
    .D(_075_),
    .Q(baud_counter[11]),
    .RESET_B(_041_)
  );
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(clk),
    .D(_076_),
    .Q(baud_counter[12]),
    .RESET_B(_042_)
  );
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(clk),
    .D(_077_),
    .Q(baud_counter[13]),
    .RESET_B(_043_)
  );
endmodule
