/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "rtl/UART_8N1_RX.v:2.1-100.10" *)
module UART_8N1_RX(RX, clk, rst, data);
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  wire [1:0] _00_;
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  wire [13:0] _01_;
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  wire [3:0] _02_;
  (* src = "rtl/UART_8N1_RX.v:57.37-57.53" *)
  (* unused_bits = "14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _03_;
  (* src = "rtl/UART_8N1_RX.v:70.40-70.55" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "rtl/UART_8N1_RX.v:46.21-46.41" *)
  wire _16_;
  (* src = "rtl/UART_8N1_RX.v:61.21-61.37" *)
  wire _17_;
  (* src = "rtl/UART_8N1_RX.v:68.25-68.45" *)
  wire _18_;
  wire [3:0] _19_;
  wire [3:0] _20_;
  wire _21_;
  wire [3:0] _22_;
  wire [3:0] _23_;
  wire _24_;
  wire _25_;
  wire [13:0] _26_;
  wire _27_;
  wire [13:0] _28_;
  wire [13:0] _29_;
  wire [13:0] _30_;
  wire [1:0] _31_;
  wire [1:0] _32_;
  wire [1:0] _33_;
  wire [1:0] _34_;
  wire [1:0] _35_;
  (* src = "rtl/UART_8N1_RX.v:3.7-3.9" *)
  input RX;
  wire RX;
  (* src = "rtl/UART_8N1_RX.v:8.12-8.17" *)
  reg [1:0] STATE;
  (* src = "rtl/UART_8N1_RX.v:12.13-12.25" *)
  reg [13:0] baud_counter;
  (* src = "rtl/UART_8N1_RX.v:13.12-13.23" *)
  reg [3:0] bit_counter;
  (* src = "rtl/UART_8N1_RX.v:4.7-4.10" *)
  input clk;
  wire clk;
  (* src = "rtl/UART_8N1_RX.v:6.18-6.22" *)
  output [7:0] data;
  reg [7:0] data;
  (* src = "rtl/UART_8N1_RX.v:11.12-11.20" *)
  reg [7:0] data_reg;
  (* src = "rtl/UART_8N1_RX.v:9.6-9.10" *)
  reg rff1;
  (* src = "rtl/UART_8N1_RX.v:10.6-10.10" *)
  reg rff2;
  (* src = "rtl/UART_8N1_RX.v:5.7-5.10" *)
  input rst;
  wire rst;
  assign _04_ = bit_counter + (* src = "rtl/UART_8N1_RX.v:70.40-70.55" *) 32'd1;
  assign _03_ = baud_counter + (* src = "rtl/UART_8N1_RX.v:87.37-87.53" *) 32'd1;
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_counter <= 4'h0;
    else if (_11_) bit_counter <= _02_;
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  always @(posedge clk, posedge rst)
    if (rst) data_reg <= 8'h00;
    else if (_12_) data_reg <= { rff2, data_reg[7:1] };
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  always @(posedge clk, posedge rst)
    if (rst) data <= 8'h00;
    else if (_13_) data <= data_reg;
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  always @(posedge clk, posedge rst)
    if (rst) baud_counter <= 14'h0000;
    else if (_08_) baud_counter <= _01_;
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  always @(posedge clk, posedge rst)
    if (rst) STATE <= 2'h0;
    else if (_14_) STATE <= _00_;
  assign _05_ = { _24_, _16_ } != 2'h2;
  assign _06_ = { _21_, _18_, _17_ } != 3'h4;
  assign _07_ = | { _25_, _24_, _21_ };
  assign _08_ = | { _27_, _25_, _24_, _21_ };
  assign _09_ = { _21_, _17_ } != 2'h2;
  assign _10_ = { _27_, _18_ } != 2'h2;
  assign _15_ = ~ _17_;
  assign _11_ = & { _05_, _07_, _06_ };
  assign _12_ = & { _15_, _21_, _18_ };
  assign _13_ = & { _27_, _18_, rff2 };
  assign _14_ = & { _09_, _10_, _08_, _05_ };
  assign _16_ = baud_counter == (* src = "rtl/UART_8N1_RX.v:46.21-46.41" *) 14'h0a2b;
  assign _17_ = bit_counter == (* src = "rtl/UART_8N1_RX.v:61.21-61.37" *) 4'h8;
  assign _18_ = baud_counter == (* src = "rtl/UART_8N1_RX.v:79.21-79.41" *) 14'h1457;
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  always @(posedge clk, posedge rst)
    if (rst) rff1 <= 1'h1;
    else rff1 <= RX;
  (* src = "rtl/UART_8N1_RX.v:20.2-99.5" *)
  always @(posedge clk, posedge rst)
    if (rst) rff2 <= 1'h1;
    else rff2 <= rff1;
  assign _19_ = _18_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:68.25-68.45|rtl/UART_8N1_RX.v:68.21-75.24" *) _04_[3:0] : 4'hx;
  assign _20_ = _17_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:61.21-61.37|rtl/UART_8N1_RX.v:61.17-76.20" *) 4'h0 : _19_;
  function [3:0] _61_;
    input [3:0] a;
    input [11:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "rtl/UART_8N1_RX.v:0.0-0.0|rtl/UART_8N1_RX.v:33.9-97.16" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _61_ = b[3:0];
      3'b?1?:
        _61_ = b[7:4];
      3'b1??:
        _61_ = b[11:8];
      default:
        _61_ = a;
    endcase
  endfunction
  assign _02_ = _61_(4'hx, { _22_, _23_, _20_ }, { _25_, _24_, _21_ });
  assign _23_ = _16_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:46.21-46.41|rtl/UART_8N1_RX.v:46.17-58.20" *) _22_ : 4'hx;
  assign _22_ = rff2 ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:36.21-36.30|rtl/UART_8N1_RX.v:36.17-43.20" *) bit_counter : 4'h0;
  function [13:0] _64_;
    input [13:0] a;
    input [55:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "rtl/UART_8N1_RX.v:0.0-0.0|rtl/UART_8N1_RX.v:33.9-97.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _64_ = b[13:0];
      4'b??1?:
        _64_ = b[27:14];
      4'b?1??:
        _64_ = b[41:28];
      4'b1???:
        _64_ = b[55:42];
      default:
        _64_ = a;
    endcase
  endfunction
  assign _01_ = _64_(14'hxxxx, { _29_, _30_, _28_, _26_ }, { _25_, _24_, _21_, _27_ });
  assign _26_ = _18_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:68.25-68.45|rtl/UART_8N1_RX.v:68.21-75.24" *) 14'h0000 : _03_[13:0];
  assign _28_ = _17_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:61.21-61.37|rtl/UART_8N1_RX.v:61.17-76.20" *) 14'h0000 : _26_;
  assign _30_ = _16_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:46.21-46.41|rtl/UART_8N1_RX.v:46.17-58.20" *) _29_ : _03_[13:0];
  assign _29_ = rff2 ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:36.21-36.30|rtl/UART_8N1_RX.v:36.17-43.20" *) baud_counter : 14'h0000;
  assign _31_ = _18_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:79.21-79.41|rtl/UART_8N1_RX.v:79.17-88.20" *) 2'h0 : 2'hx;
  function [1:0] _70_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "rtl/UART_8N1_RX.v:0.0-0.0|rtl/UART_8N1_RX.v:33.9-97.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _70_ = b[1:0];
      4'b??1?:
        _70_ = b[3:2];
      4'b?1??:
        _70_ = b[5:4];
      4'b1???:
        _70_ = b[7:6];
      default:
        _70_ = a;
    endcase
  endfunction
  assign _00_ = _70_(2'hx, { _35_, _34_, _32_, _31_ }, { _25_, _24_, _21_, _27_ });
  assign _32_ = _17_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:61.21-61.37|rtl/UART_8N1_RX.v:61.17-76.20" *) 2'h3 : 2'hx;
  assign _21_ = STATE == (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:0.0-0.0|rtl/UART_8N1_RX.v:33.9-97.16" *) 2'h2;
  assign _33_ = rff2 ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:47.25-47.34|rtl/UART_8N1_RX.v:47.21-54.24" *) 2'h0 : 2'h2;
  assign _34_ = _16_ ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:46.21-46.41|rtl/UART_8N1_RX.v:46.17-58.20" *) _33_ : 2'hx;
  assign _24_ = STATE == (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:0.0-0.0|rtl/UART_8N1_RX.v:33.9-97.16" *) 2'h1;
  assign _35_ = rff2 ? (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:36.21-36.30|rtl/UART_8N1_RX.v:36.17-43.20" *) 2'h0 : 2'h1;
  assign _25_ = ! (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:0.0-0.0|rtl/UART_8N1_RX.v:33.9-97.16" *) STATE;
  assign _27_ = STATE == (* full_case = 32'd1 *) (* src = "rtl/UART_8N1_RX.v:0.0-0.0|rtl/UART_8N1_RX.v:33.9-97.16" *) 2'h3;
endmodule
